### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by rainharp** [Berreman4x4/Berreman4x4#2]
when I run Bragg-example.py, it raised an AttributeError: **module 'scipy.linalg' has no attribute 'expm2'.**
and for cholesteric-example.py, it raised a TypeError: **expm() takes 1 positional argument but 2 were given.**

Runtime environment:  Python 3.7.0, numpy-1.15.1, scipy-1.1.0, matplotlib-2.2.3

**Comment by ocastany** [comment]
It was corrected some time ago. The delay is because I didn't see this issue request.
